### ISSUE TITLE
support for universal dep labels

### ISSUE THREAD

**Issue by geovedi** [attardi/DgAnnotator#1]
Hi, 

Any plan to add unideps support? Also would be great if user can edit the arcs.

Cheers.

**Comment by attardi** [comment]
On 7/3/2015 15:29, Jim Geovedi wrote:

> Hi,
> 
> Any plan to add unideps support? Also would be great if user can edit 
> the arcs.
> 
> Cheers.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/attardi/DgAnnotator/issues/1.
> 
> The current version released here
>      http://medialab.di.unipi.it/Project/QA/Parser/DgAnnotator/
> suppports UD format: specify .conllu extension.

-- Beppe
